// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDURijjQJ-rhifoqpDLwh7ShLDv7F0K9Lk',
    appId: '1:594006848019:web:78db22f61eaf0a14f205e6',
    messagingSenderId: '594006848019',
    projectId: 'dashdeliveries-bb312',
    authDomain: 'dashdeliveries-bb312.firebaseapp.com',
    storageBucket: 'dashdeliveries-bb312.appspot.com',
    measurementId: 'G-EJRFKTKMHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYE9C9tQ3UpbeqNlup7sVmx-M4gdJ8zXo',
    appId: '1:594006848019:android:140bf5b9cb2bf231f205e6',
    messagingSenderId: '594006848019',
    projectId: 'dashdeliveries-bb312',
    storageBucket: 'dashdeliveries-bb312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApnw_tyngHaHBdV7CgneKRxcsbe5FG9wg',
    appId: '1:594006848019:ios:03e13d3040404c6af205e6',
    messagingSenderId: '594006848019',
    projectId: 'dashdeliveries-bb312',
    storageBucket: 'dashdeliveries-bb312.appspot.com',
    iosBundleId: 'com.milestone.dashletDeliveries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApnw_tyngHaHBdV7CgneKRxcsbe5FG9wg',
    appId: '1:594006848019:ios:03e13d3040404c6af205e6',
    messagingSenderId: '594006848019',
    projectId: 'dashdeliveries-bb312',
    storageBucket: 'dashdeliveries-bb312.appspot.com',
    iosBundleId: 'com.milestone.dashletDeliveries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDURijjQJ-rhifoqpDLwh7ShLDv7F0K9Lk',
    appId: '1:594006848019:web:793eaed13e3622b9f205e6',
    messagingSenderId: '594006848019',
    projectId: 'dashdeliveries-bb312',
    authDomain: 'dashdeliveries-bb312.firebaseapp.com',
    storageBucket: 'dashdeliveries-bb312.appspot.com',
    measurementId: 'G-RPHGR76977',
  );
}
